services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container
    command: redis-server --requirepass pass
    ports:
      - "6380:6379"
    volumes:
      - redis_volume:/data

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: my-bucket
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  db_volume:
  redis_volume:
  minio_data: