services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume: