server:
  port: 8080

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cloud_db
    username: postgres
    password: pass
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  flyway:
    url: jdbc:postgresql://localhost:5433/cloud_db
    user: postgres
    password: pass
    callback-locations: db/migration

  data:
    redis:
      port: 6380
      host: localhost
