server:
  port: 8080

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  root-bucket: "user-files"

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}


  flyway:
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    callback-locations: db/migration

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}


  config:
    import: optional:file:.env.dev[.properties]
